# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-backend-5ig67zl4vi6sc
env:
    VITE_SEGMENT_WRITE_KEY: Meqq3oEiI4z16z7CuBDyUGzDvw97LkOA

on:
    push:
        branches:
            - staging

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Build frontend
              working-directory: frontend
              run: |
                  npm install
                  npm run build

            - name: Set up Python version
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Create and start virtual environment
              working-directory: app
              run: |
                  python -m venv venv
                  source venv/bin/activate

            - name: Set up dependency caching for faster installs
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              working-directory: app
              run: pip install -r requirements.txt

            - name: Upload artifact for deployment jobs
              uses: actions/upload-artifact@v4
              with:
                  name: python-app
                  path: app/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: python-app
                  path: .

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v2
              id: deploy-to-webapp
              with:
                  app-name: "app-backend-5ig67zl4vi6sc"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4080EE14FA774752B22DE44221DB90D4 }}
